export default {
	installation: "Installation",
	settings: "Setting page",
	general: "General options",
	button: "Button",
	modal: "Modal",
	product: "product",
	button: "Button customization",
	modal: "Modal customization",
	product: "Product customization",
	"product-navigation": "Product navigation",
	"related-product": "Related product",
	"social-share": "Social Share",
	developer: "Developer",
};
